### ISSUE TITLE
Instance ID template macro

### ISSUE THREAD

**Issue by codesmaker** [miyahan/Zabbix_EC2_meta-data_check#1]
Hi,

First of all, thanks a lot for the very helpful scripts you created and for the detailed explanation.

I'm a little bit confused about the instance ID macros. Why did you fix it as a template macro? Doesn't it change?

Is it possible to use the item's value (EC2 instance-id) which is the instance ID you get by running the curl command as a parameter to your Python script to terminate the instance?

**Comment by miyahan** [comment]
Hi.

instance-id and instance-status items need to be separated  because each source is different (zabbix-server get the instance-id via zabbix-agent and the instance-status via AWS SDK). However, Zabbix's external checks item cannot refer to other item values ​​in parameters. So I use user-macro to refer to instance-id.  #  Please let me know if you have any better ideas.

When the instance-id is changed, server is registered as a new Zabbix host. I designed it on the premise that instances are thrown away by AutoScaling.

**Comment by codesmaker** [comment]
Thanks for your answer.

OK. What still confuses me is that the template macro "{$EC2_INSTANCEID}" is set to "unknown". How do you update that macro based on the value of "EC2 instance-id" item?

Here is the key you use to check the state of an instance:
`get_ec2_status.py[-r,{$REGION},-a,{$KEY},-s,{$SECRET},-i,{$EC2_INSTANCEID}]`

From what I can see, the "$EC2_INSTANCEID" macro's value is always set to 'unknown'.

**Comment by miyahan** [comment]
Is `EC2 instance-id` Zabbix **item** value an instance-id?

If the value is empty or an error, make sure you can get the metadata using curl command on Zabbix agent host.
cmd: `curl -s -f http://169.254.169.254/latest/meta-data/instance-id`

On the other hand, if the value is the correct instance-id, the set of user macros may have failed. Check the zabbix-agent log. Also, try to run a Python script that sets instance-id to user-macro on Zabbix server host.
cmd `/path/to/get_ec2_status.py -r <REGION> -a <ACCESS_KEY> -s <SECRE_KEY> -i <EC2_INSTANCEID> `

**Comment by codesmaker** [comment]
According to the way you did it, you defined a template macro called "$EC2_INSTANCEID" and then you set the value to "unknown". My question was this macro is never set and thus, the "get_ec2_status.py" script always returns unknown so how you pass the instance id to the "get_ec2_status.py" script?

In another words, let's say that there is an item that is called "get instanceid" with a key:
`curl -s -f http://169.254.169.254/latest/meta-data/instance-id`
which is executed by the Zabbix agent.

My question is: how to feed the returned value of "get instanceid" item to the "get_ec2_status.py" script to get the instance state?

**Comment by miyahan** [comment]
Sorry for my poor understanding English. Indicates the flow:

1. `EC2 instance-id` item periodically collects and stores instance-id using curl.
1. `Register instance-id` trigger runs "register_ec2_instanceid.py" script when value of `EC2 instance-id` item was changed.
1. "register_ec2_instanceid.py" script set  instance-id to host's `{$ EC2_INSTANCEID}` macro using Zabbix API. (**Here,  value of macro changes from "unknown".**)
1. `EC2 instance state` item periodically calls "get_ec2_status.py" script and updates item value.

**Comment by codesmaker** [comment]
Not at all. Your English is good and clear.

OK, now I understand how the {$EC2_INSTANCEID} macro gets changed from unknown to the actual instance ID. Thanks a lot for your explanation.

Actually, I learned a lot for your approach but I'm trying to do it in a different way by using low level discovery. I create a discovery rule that gets the instance ID and then I use it to get the status of the instance by using an item prototype. By doing so, an item, that checks the instance id, gets created automatically with every new registered instance.

When I need to terminate the instance, let's say because it's idle for more than 10 mins, I need to pass the instance ID to an external script. The problem is that I don't know how to pass the value of an item as a parameter for a script executed by another item. You said that it isn't possible? There is no workaround for that?

**Comment by miyahan** [comment]
I previously discussed it in Japan Zabbix user community and concluded that, except for calculated items, the value of other items can't be used in item keys.

Only these macros can be used in item keys:
https://www.zabbix.com/documentation/4.0/manual/appendix/macros/supported_by_location

I have no idea other than using user macros like public variables.

**Comment by codesmaker** [comment]
Got it.

Thanks a lot for all the info and the help!
