### ISSUE TITLE
Error while running delete_host.py

### ISSUE THREAD

**Issue by codesmaker** [miyahan/Zabbix_EC2_meta-data_check#2]
Hi,

I'm trying to run "delete_host.py" script like this:
`./delete_host.py -n myhost`

But I'm getting this error:
Traceback (most recent call last):
  File "./delete_host.py", line 26, in <module>
    'output': ['name', 'hostid']
TypeError: do_request() takes exactly 2 arguments (3 given)

Could you please help?

**Comment by miyahan** [comment]
This problem could not be reproduced in my environment.

```
# python -V
Python 2.7.16
# pip freeze | grep py-zabbix
py-zabbix==1.1.3

# python3 -V
Python 3.6.8
# pip-3.6 freeze | grep py-zabbix
py-zabbix==1.1.5
```

The spec of py-zabbix's `do_request()` method seems different from what I know. Try updating your Python and libraries using OS package manager and PIP. Also check that installed library is correct. This program needs [py-zabbix](https://pypi.org/project/py-zabbix/).

In addition, make sure that py-zabbix works alone.

**Comment by codesmaker** [comment]
Thanks for your reply.

After checking everything you mentioned and all was good. I re-cloned your repository and tried. It worked. It seems I forgot that I modified your python script a little bit which it rendered it broken.

My apologies for the noise and thanks a lot for your help.

Cheers.
